# Generated by Django 6.0.2 on 2026-03-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('category', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('author', models.CharField(default='Honey Group', max_length=120)),
                ('readTime', models.CharField(blank=True, default='', max_length=20)),
                ('cover', models.CharField(max_length=255)),
                ('images', models.JSONField(blank=True, default=list)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('content', models.JSONField(blank=True, default=list)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('durationLabel', models.CharField(blank=True, default='', max_length=60)),
                ('routeLabel', models.CharField(blank=True, default='', max_length=140)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('cover', models.CharField(max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('gallery', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('zone', models.CharField(blank=True, default='', max_length=80)),
                ('teaser', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('cover', models.CharField(max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('gallery', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('durationLabel', models.CharField(blank=True, default='', max_length=60)),
                ('area', models.CharField(blank=True, default='', max_length=120)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('cover', models.CharField(max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('gallery', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HeroMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='youtube', max_length=20)),
                ('poster', models.CharField(blank=True, default='', max_length=255)),
                ('youtubeId', models.CharField(blank=True, default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('duration', models.CharField(blank=True, default='', max_length=60)),
                ('description', models.TextField(blank=True, default='')),
                ('bullets', models.JSONField(blank=True, default=list)),
                ('cover', models.CharField(max_length=255)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('platform', models.CharField(blank=True, default='YouTube', max_length=40)),
                ('url', models.URLField()),
                ('thumbnail', models.URLField(blank=True, default='')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
