# Generated by Django 6.0.2 on 2026-03-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocard',
            options={'ordering': ['order', '-featured', 'title']},
        ),
        migrations.RemoveField(
            model_name='videocard',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='videocard',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='videocard',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='videocard',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocard',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='heromedia',
            name='id',
            field=models.CharField(default='hero', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='heromedia',
            name='mode',
            field=models.CharField(default='youtube', max_length=32),
        ),
        migrations.AlterField(
            model_name='heromedia',
            name='youtubeId',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='title',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
